export const testDirections = [
{id: '1',
label: 'UX/UI Дизайн'},
{id: '2',
label: 'Frontend'},
{id: '3',
label: 'Fullstack'},
{id: '4',
label: 'Backend'},
{id: '5',
label: 'DevOps'},
{id: '6',
label: 'Системная аналитика'},
{id: '7',
label: 'Data Science'},
{id: '8',
label: 'QA Тестирование'},
{id: '9',
label: 'Менеджмент'},
{id: '10',
label: 'Системная аналитика'},
{id: '11',
label: 'Data Science'},
{id: '12',
label: 'QA Тестирование'},
{id: '13',
label: 'Менеджмент'},
]
