export const gradeElementTableStyles = {
  junior: {
    borderRadius: '4px',
    border: '1px solid #DDE0E4',
    backgroundColor: '#FFF9D3',
    paddingTop: '8px',
    paddingBottom: '8px',
    paddingLeft: '12px',
    paddingRight: '12px',
    alignText: 'center',
    fontSize: '14px',
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: '20px',
  },
  middle: {
    borderRadius: '4px',
    border: '1px solid #DDE0E4',
    backgroundColor: '#C2E5CE',
    paddingTop: '8px',
    paddingBottom: '8px',
    paddingLeft: '12px',
    paddingRight: '12px',
    alignText: 'center',
    fontSize: '14px',
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: '20px',
  },
  senior: {
    borderRadius: '4px',
    border: '1px solid #DDE0E4',
    backgroundColor: '#ACCCFF',
    paddingTop: '8px',
    paddingBottom: '8px',
    paddingLeft: '12px',
    paddingRight: '12px',
    alignText: 'center',
    fontSize: '14px',
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: '20px',
  },

};
