name: Alert
on:
  workflow_dispatch:
  push: push
  
jobs:
  alert: 
    runs-on: ubuntu-latest
    steps:
     
     
     
      - name: Отправка сообщения в группу telegram
        uses: colutius/Telegram-Msg@main
        with:
          chatid: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          disable_notification: true
          message: |
            @${{ github.actor }} отправил: ${{ github.event.commits[0].message }}
          button: true
          button_name: Посмотреть изменения
          button_url: https://github.com/${{ github.repository }}/commit/${{github.sha}}
          is_notify: false
          is_preview: false

